//
//  StubJsonData.swift
//  FOFMAPTests
//
//  Created by 강민수 on 2023/07/02.
//

import UIKit

struct SampleData {
    static let userInfo = """
    {
        "accessId": "68bb3f88b9b7e862a2639a9d",
        "nickname": "민수쨔응",
        "level": 60
    }
    """.data(using: .utf8)!
    
    static let matchIds = """
    [
            "5d25fa0fea00678d61010bd7",
            "5d25fa336325f381bc55fad5",
            "5d25fa380758fe690757bd81",
            "5d25fa3c13a97367e6e4ae6e"
    ]
    """.data(using: .utf8)!
    
    static let userTradeHistoryData = """
    [
         {
             "tradeDate": "2023-02-19T12:05:23",
             "saleSn": "63f191f21fe6bb1531970ac4",
             "spid": 259208574,
             "grade": 1,
             "value": 2700000000
         },
         {
             "tradeDate": "2023-02-19T12:05:07",
             "saleSn": "63f191e07cca70dbc97ceb7e",
             "spid": 259252371,
             "grade": 1,
             "value": 2710000000
         }
    ]
    """.data(using: .utf8)!
    
    static let imageData = UIImage(systemName: "person.fill")!.pngData()!
    
    static let matchDescData = """
    {
            "matchId": "64a63b7baf49b7c8607bc70f",
            "matchDate": "2023-07-06T12:59:30",
            "matchType": 50,
            "matchInfo": [
                    {
                            "accessId": "838f91d858ba1582148353f5",
                            "nickname": "똥볼차는맹구",
                            "matchDetail": {
                                    "seasonId": 202307,
                                    "matchResult": "패",
                                    "matchEndType": 2,
                                    "systemPause": 1,
                                    "foul": 0,
                                    "injury": 0,
                                    "redCards": 0,
                                    "yellowCards": 0,
                                    "dribble": 9,
                                    "cornerKick": 0,
                                    "possession": 40,
                                    "offsideCount": 0,
                                    "averageRating": 3.16111,
                                    "controller": "keyboard"
                            },
                            "shoot": {
                                    "shootTotal": 0,
                                    "effectiveShootTotal": 0,
                                    "shootOutScore": 0,
                                    "goalTotal": 0,
                                    "goalTotalDisplay": 0,
                                    "ownGoal": 0,
                                    "shootHeading": 0,
                                    "goalHeading": 0,
                                    "shootFreekick": 0,
                                    "goalFreekick": 0,
                                    "shootInPenalty": 0,
                                    "goalInPenalty": 0,
                                    "shootOutPenalty": 0,
                                    "goalOutPenalty": 0,
                                    "shootPenaltyKick": 0,
                                    "goalPenaltyKick": 0
                            },
                            "shootDetail": [
                                    {
                                            "goalTime": 0,
                                            "x": 0,
                                            "y": 0,
                                            "type": 0,
                                            "result": 0,
                                            "spId": 0,
                                            "spGrade": 0,
                                            "spLevel": 0,
                                            "spIdType": false,
                                            "assist": false,
                                            "assistSpId": 0,
                                            "assistX": 0,
                                            "assistY": 0,
                                            "hitPost": false,
                                            "inPenalty": false
                                    }
                            ],
                            "pass": {
                                    "passTry": 20,
                                    "passSuccess": 17,
                                    "shortPassTry": 15,
                                    "shortPassSuccess": 15,
                                    "longPassTry": 1,
                                    "longPassSuccess": 0,
                                    "bouncingLobPassTry": 0,
                                    "bouncingLobPassSuccess": 0,
                                    "drivenGroundPassTry": 1,
                                    "drivenGroundPassSuccess": 1,
                                    "throughPassTry": 3,
                                    "throughPassSuccess": 1,
                                    "lobbedThroughPassTry": 0,
                                    "lobbedThroughPassSuccess": 0
                            },
                            "defence": {
                                    "blockTry": 7,
                                    "blockSuccess": 0,
                                    "tackleTry": 1,
                                    "tackleSuccess": 1
                            },
                            "player": [
                                    {
                                            "spId": 272037576,
                                            "spPosition": 25,
                                            "spGrade": 5,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 5,
                                                    "passSuccess": 5,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 6
                                            }
                                    },
                                    {
                                            "spId": 280165153,
                                            "spPosition": 21,
                                            "spGrade": 5,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 3,
                                                    "passSuccess": 3,
                                                    "dribbleTry": 1,
                                                    "dribbleSuccess": 1,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 6.1
                                            }
                                    },
                                    {
                                            "spId": 279182521,
                                            "spPosition": 11,
                                            "spGrade": 5,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 5,
                                                    "passSuccess": 4,
                                                    "dribbleTry": 4,
                                                    "dribbleSuccess": 4,
                                                    "ballPossesionTry": 1,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 1,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 5.8
                                            }
                                    },
                                    {
                                            "spId": 300192119,
                                            "spPosition": 0,
                                            "spGrade": 5,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 1,
                                                    "passTry": 1,
                                                    "passSuccess": 1,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 1,
                                                    "ballPossesionSuccess": 1,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 5.7
                                            }
                                    },
                                    {
                                            "spId": 260235212,
                                            "spPosition": 3,
                                            "spGrade": 6,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 0,
                                                    "passSuccess": 0,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 1,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 4.3
                                            }
                                    },
                                    {
                                            "spId": 511235243,
                                            "spPosition": 28,
                                            "spGrade": 1,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 0,
                                                    "passSuccess": 0,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 0
                                            }
                                    },
                                    {
                                            "spId": 280238794,
                                            "spPosition": 16,
                                            "spGrade": 5,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 3,
                                                    "passSuccess": 1,
                                                    "dribbleTry": 2,
                                                    "dribbleSuccess": 2,
                                                    "ballPossesionTry": 2,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 5.2
                                            }
                                    },
                                    {
                                            "spId": 260243812,
                                            "spPosition": 12,
                                            "spGrade": 5,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 0,
                                                    "passSuccess": 0,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 4.3
                                            }
                                    },
                                    {
                                            "spId": 511246104,
                                            "spPosition": 28,
                                            "spGrade": 1,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 0,
                                                    "passSuccess": 0,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 0
                                            }
                                    },
                                    {
                                            "spId": 300256790,
                                            "spPosition": 28,
                                            "spGrade": 1,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 0,
                                                    "passSuccess": 0,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 0
                                            }
                                    },
                                    {
                                            "spId": 283197445,
                                            "spPosition": 9,
                                            "spGrade": 5,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 1,
                                                    "passSuccess": 1,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 4.5
                                            }
                                    },
                                    {
                                            "spId": 300203376,
                                            "spPosition": 28,
                                            "spGrade": 2,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 0,
                                                    "passSuccess": 0,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 0
                                            }
                                    },
                                    {
                                            "spId": 270205452,
                                            "spPosition": 4,
                                            "spGrade": 5,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 1,
                                                    "passSuccess": 1,
                                                    "dribbleTry": 1,
                                                    "dribbleSuccess": 1,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 3,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 4.6
                                            }
                                    },
                                    {
                                            "spId": 511205705,
                                            "spPosition": 28,
                                            "spGrade": 1,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 0,
                                                    "passSuccess": 0,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 0
                                            }
                                    },
                                    {
                                            "spId": 300222492,
                                            "spPosition": 28,
                                            "spGrade": 1,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 0,
                                                    "passSuccess": 0,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 0
                                            }
                                    },
                                    {
                                            "spId": 260228618,
                                            "spPosition": 7,
                                            "spGrade": 5,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 1,
                                                    "passSuccess": 1,
                                                    "dribbleTry": 1,
                                                    "dribbleSuccess": 1,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 4.8
                                            }
                                    },
                                    {
                                            "spId": 280232656,
                                            "spPosition": 6,
                                            "spGrade": 5,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 1,
                                                    "defending": 0,
                                                    "passTry": 0,
                                                    "passSuccess": 0,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 2,
                                                    "block": 0,
                                                    "tackleTry": 1,
                                                    "tackle": 1,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 5.6
                                            }
                                    },
                                    {
                                            "spId": 225232997,
                                            "spPosition": 28,
                                            "spGrade": 1,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 0,
                                                    "passSuccess": 0,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 0
                                            }
                                    }
                            ]
                    },
                    {
                            "accessId": "6afff19af7d73f48c1b069a4",
                            "nickname": "진식이는스콜스",
                            "matchDetail": {
                                    "seasonId": 202307,
                                    "matchResult": "승",
                                    "matchEndType": 1,
                                    "systemPause": 0,
                                    "foul": 0,
                                    "injury": 0,
                                    "redCards": 0,
                                    "yellowCards": 0,
                                    "dribble": 22,
                                    "cornerKick": 0,
                                    "possession": 60,
                                    "offsideCount": 0,
                                    "averageRating": 4.42778,
                                    "controller": "keyboard"
                            },
                            "shoot": {
                                    "shootTotal": 4,
                                    "effectiveShootTotal": 3,
                                    "shootOutScore": 0,
                                    "goalTotal": 3,
                                    "goalTotalDisplay": 3,
                                    "ownGoal": 0,
                                    "shootHeading": 0,
                                    "goalHeading": 0,
                                    "shootFreekick": 0,
                                    "goalFreekick": 0,
                                    "shootInPenalty": 4,
                                    "goalInPenalty": 3,
                                    "shootOutPenalty": 0,
                                    "goalOutPenalty": 0,
                                    "shootPenaltyKick": 0,
                                    "goalPenaltyKick": 0
                            },
                            "shootDetail": [
                                    {
                                            "goalTime": 230,
                                            "x": 0.8780531883239746,
                                            "y": 0.4013926684856415,
                                            "type": 6,
                                            "result": 2,
                                            "spId": 280202126,
                                            "spGrade": 5,
                                            "spLevel": 5,
                                            "spIdType": true,
                                            "assist": true,
                                            "assistSpId": 251013743,
                                            "assistX": 0.8026145100593567,
                                            "assistY": 0.4555005431175232,
                                            "hitPost": false,
                                            "inPenalty": true
                                    },
                                    {
                                            "goalTime": 390,
                                            "x": 0.8927114009857178,
                                            "y": 0.5278364419937134,
                                            "type": 2,
                                            "result": 3,
                                            "spId": 280202126,
                                            "spGrade": 5,
                                            "spLevel": 5,
                                            "spIdType": true,
                                            "assist": true,
                                            "assistSpId": 260202652,
                                            "assistX": 0.7710049748420715,
                                            "assistY": 0.3649729192256927,
                                            "hitPost": false,
                                            "inPenalty": true
                                    },
                                    {
                                            "goalTime": 682,
                                            "x": 0.8976287245750427,
                                            "y": 0.5359807014465332,
                                            "type": 6,
                                            "result": 3,
                                            "spId": 101000246,
                                            "spGrade": 3,
                                            "spLevel": 5,
                                            "spIdType": true,
                                            "assist": true,
                                            "assistSpId": 101005419,
                                            "assistX": 0.8621964454650879,
                                            "assistY": 0.6468055844306946,
                                            "hitPost": false,
                                            "inPenalty": true
                                    },
                                    {
                                            "goalTime": 1131,
                                            "x": 0.9240453243255616,
                                            "y": 0.5066401958465576,
                                            "type": 2,
                                            "result": 3,
                                            "spId": 260202652,
                                            "spGrade": 6,
                                            "spLevel": 5,
                                            "spIdType": true,
                                            "assist": true,
                                            "assistSpId": 101005419,
                                            "assistX": 0.9041368961334229,
                                            "assistY": 0.3786844313144684,
                                            "hitPost": false,
                                            "inPenalty": true
                                    }
                            ],
                            "pass": {
                                    "passTry": 26,
                                    "passSuccess": 26,
                                    "shortPassTry": 17,
                                    "shortPassSuccess": 17,
                                    "longPassTry": 0,
                                    "longPassSuccess": 0,
                                    "bouncingLobPassTry": 0,
                                    "bouncingLobPassSuccess": 0,
                                    "drivenGroundPassTry": 2,
                                    "drivenGroundPassSuccess": 2,
                                    "throughPassTry": 7,
                                    "throughPassSuccess": 7,
                                    "lobbedThroughPassTry": 0,
                                    "lobbedThroughPassSuccess": 0
                            },
                            "defence": {
                                    "blockTry": 2,
                                    "blockSuccess": 0,
                                    "tackleTry": 0,
                                    "tackleSuccess": 0
                            },
                            "player": [
                                    {
                                            "spId": 101000246,
                                            "spPosition": 9,
                                            "spGrade": 3,
                                            "status": {
                                                    "shoot": 1,
                                                    "effectiveShoot": 1,
                                                    "assist": 0,
                                                    "goal": 1,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 4,
                                                    "passSuccess": 4,
                                                    "dribbleTry": 3,
                                                    "dribbleSuccess": 3,
                                                    "ballPossesionTry": 2,
                                                    "ballPossesionSuccess": 1,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 7
                                            }
                                    },
                                    {
                                            "spId": 101005419,
                                            "spPosition": 25,
                                            "spGrade": 3,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 2,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 8,
                                                    "passSuccess": 8,
                                                    "dribbleTry": 5,
                                                    "dribbleSuccess": 5,
                                                    "ballPossesionTry": 1,
                                                    "ballPossesionSuccess": 1,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 10
                                            }
                                    },
                                    {
                                            "spId": 256007289,
                                            "spPosition": 4,
                                            "spGrade": 5,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 0,
                                                    "passSuccess": 0,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 6.4
                                            }
                                    },
                                    {
                                            "spId": 251013743,
                                            "spPosition": 11,
                                            "spGrade": 5,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 4,
                                                    "passSuccess": 4,
                                                    "dribbleTry": 3,
                                                    "dribbleSuccess": 3,
                                                    "ballPossesionTry": 1,
                                                    "ballPossesionSuccess": 1,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 6.8
                                            }
                                    },
                                    {
                                            "spId": 206203841,
                                            "spPosition": 0,
                                            "spGrade": 7,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 0,
                                                    "passSuccess": 0,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 6.4
                                            }
                                    },
                                    {
                                            "spId": 260229984,
                                            "spPosition": 7,
                                            "spGrade": 6,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 2,
                                                    "passSuccess": 2,
                                                    "dribbleTry": 2,
                                                    "dribbleSuccess": 2,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 6.8
                                            }
                                    },
                                    {
                                            "spId": 510234222,
                                            "spPosition": 28,
                                            "spGrade": 5,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 0,
                                                    "passSuccess": 0,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 0
                                            }
                                    },
                                    {
                                            "spId": 300234742,
                                            "spPosition": 28,
                                            "spGrade": 1,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 0,
                                                    "passSuccess": 0,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 0
                                            }
                                    },
                                    {
                                            "spId": 260238074,
                                            "spPosition": 3,
                                            "spGrade": 5,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 0,
                                                    "passSuccess": 0,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 1,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 6.4
                                            }
                                    },
                                    {
                                            "spId": 300239703,
                                            "spPosition": 28,
                                            "spGrade": 4,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 0,
                                                    "passSuccess": 0,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 0
                                            }
                                    },
                                    {
                                            "spId": 202044786,
                                            "spPosition": 28,
                                            "spGrade": 1,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 0,
                                                    "passSuccess": 0,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 0
                                            }
                                    },
                                    {
                                            "spId": 281050752,
                                            "spPosition": 6,
                                            "spGrade": 5,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 0,
                                                    "passSuccess": 0,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 6.4
                                            }
                                    },
                                    {
                                            "spId": 231164859,
                                            "spPosition": 23,
                                            "spGrade": 8,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 2,
                                                    "passSuccess": 2,
                                                    "dribbleTry": 1,
                                                    "dribbleSuccess": 1,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 1,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 6.5
                                            }
                                    },
                                    {
                                            "spId": 256188377,
                                            "spPosition": 28,
                                            "spGrade": 5,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 0,
                                                    "passSuccess": 0,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 0
                                            }
                                    },
                                    {
                                            "spId": 321192598,
                                            "spPosition": 28,
                                            "spGrade": 1,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 0,
                                                    "passSuccess": 0,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 0
                                            }
                                    },
                                    {
                                            "spId": 206193352,
                                            "spPosition": 28,
                                            "spGrade": 1,
                                            "status": {
                                                    "shoot": 0,
                                                    "effectiveShoot": 0,
                                                    "assist": 0,
                                                    "goal": 0,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 0,
                                                    "passSuccess": 0,
                                                    "dribbleTry": 0,
                                                    "dribbleSuccess": 0,
                                                    "ballPossesionTry": 0,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 0
                                            }
                                    },
                                    {
                                            "spId": 280202126,
                                            "spPosition": 18,
                                            "spGrade": 5,
                                            "status": {
                                                    "shoot": 2,
                                                    "effectiveShoot": 1,
                                                    "assist": 0,
                                                    "goal": 1,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 3,
                                                    "passSuccess": 3,
                                                    "dribbleTry": 4,
                                                    "dribbleSuccess": 4,
                                                    "ballPossesionTry": 2,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 7
                                            }
                                    },
                                    {
                                            "spId": 260202652,
                                            "spPosition": 27,
                                            "spGrade": 6,
                                            "status": {
                                                    "shoot": 1,
                                                    "effectiveShoot": 1,
                                                    "assist": 1,
                                                    "goal": 1,
                                                    "dribble": 0,
                                                    "intercept": 0,
                                                    "defending": 0,
                                                    "passTry": 3,
                                                    "passSuccess": 3,
                                                    "dribbleTry": 4,
                                                    "dribbleSuccess": 4,
                                                    "ballPossesionTry": 1,
                                                    "ballPossesionSuccess": 0,
                                                    "aerialTry": 0,
                                                    "aerialSuccess": 0,
                                                    "blockTry": 0,
                                                    "block": 0,
                                                    "tackleTry": 0,
                                                    "tackle": 0,
                                                    "yellowCards": 0,
                                                    "redCards": 0,
                                                    "spRating": 10
                                            }
                                    }
                            ]
                    }
            ]
    }
    """.data(using: .utf8)
}
